---
deployment:
  tasks:
    - /usr/local/cpanel/3rdparty/lib/path-bin/git push master origin
    - export DEPLOYPATH=/home/hanauno/nodejs/sambung-kata-api/
    - /bin/cp -R /home/hanauno/repositories/sambung-kata-api/ $DEPLOYPATH
